/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/templates/{templateId}/render': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Render an email template
     * @description Renders an email template using the provided variables and returns the HTML and plain text versions.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description The ID of the template to render. */
          templateId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /** @description Key-value pairs for template variables. */
            variables?: {
              [key: string]: unknown;
            };
            /** @description Key-value pairs for repeatable template variables. */
            repeatVariables?: {
              [key: string]: unknown;
            };
            /** @description Optional preview text for the email. */
            previewText?: string;
          };
        };
      };
      responses: {
        /** @description Successfully rendered the template. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description The rendered HTML content of the email. */
              html?: string;
              /** @description The rendered plain text content of the email. */
              plainText?: string;
            };
          };
        };
        /** @description Bad request due to invalid input. */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @example 400 */
              status?: number;
              /** @example Invalid input */
              message?: string;
              errors?: string[];
            };
          };
        };
        /** @description Unauthorized access. */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @example 401 */
              status?: number;
              /** @example Unauthorized */
              message?: string;
              errors?: string[];
            };
          };
        };
        /** @description Template not found. */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @example 404 */
              status?: number;
              /** @example Template not found */
              message?: string;
              errors?: string[];
            };
          };
        };
        /** @description Method not allowed. */
        405: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @example 405 */
              status?: number;
              /** @example Method Not Allowed */
              message?: string;
              errors?: string[];
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/templates/{templateId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Retrieve a specific email template by ID.
     * @description Fetches an email template by its ID. Requires either user authentication or a valid API key.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description The ID of the email template to retrieve. */
          templateId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Successfully retrieved the email template. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              id?: string;
              title?: string;
              preview_text?: string;
              content?: Record<string, never>;
              user_id?: string;
            };
          };
        };
        /** @description Unauthorized. User is not authenticated or API key is invalid. */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @example 401 */
              status?: number;
              /** @example Unauthorized */
              message?: string;
              errors?: string[];
            };
          };
        };
        /** @description Template not found. */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @example 404 */
              status?: number;
              /** @example Template not found */
              message?: string;
              errors?: string[];
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: never;
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
