packages:
  - 'apps/*'
  - 'packages/*'
catalog:
  '@tiptap/core': ^3.22.3
  '@tiptap/pm': ^3.22.3
  '@tiptap/react': ^3.22.3
  '@types/react': ^19.2.14
  '@types/react-dom': ^19.2.3
  '@oxlint/plugins': ^1.59.0
  bumpp: ^11.0.1
  react: ^19.2.5
  react-dom: ^19.2.5
  typescript: ^6.0.2
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
