packages:
  - 'apps/*'
  - 'packages/*'
catalog:
  '@oxlint/plugins': ^1.76.0
  '@rolldown/plugin-babel': ^0.2.3
  '@tiptap/core': ^3.29.2
  '@tiptap/pm': ^3.29.2
  '@tiptap/react': ^3.29.2
  '@types/react': ^19.2.18
  '@types/react-dom': ^19.2.4
  bumpp: ^12.1.1
  react: ^19.2.8
  react-dom: ^19.2.8
  typescript: ^7.0.2
  vite: npm:@voidzero-dev/vite-plus-core@0.1.14
  vite-plus: 0.1.14
  vitest: npm:@voidzero-dev/vite-plus-test@0.1.14
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
