packages:
  - 'apps/*'
  - 'packages/*'
catalog:
  '@tiptap/core': ^3.20.1
  '@tiptap/pm': ^3.20.1
  '@tiptap/react': ^3.20.1
  '@types/react': ^19.2.14
  '@types/react-dom': ^19.2.3
  '@oxlint/plugins': ^1.57.0
  bumpp: ^10.4.1
  react: ^19.2.4
  react-dom: ^19.2.4
  typescript: ^5.9.3
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
