name: Publish core

on:
  push:
    tags:
      - 'core@v*'

jobs:
  release:
    uses: arikchakma/workflows/.github/workflows/release-pnpm.yml@v1
    permissions:
      contents: write
      id-token: write
    with:
      publish: true
      build: pnpm run build
      publish-directory: packages/core
    secrets: inherit
